Update action.yml

diff --git a/.github/workflows/action.yml b/.github/workflows/action.yml
--- a/.github/workflows/action.yml
+++ b/.github/workflows/action.yml
@@ -39,13 +39,13 @@ jobs:
 #      - name: show job status
 #        if: always()
 #        run: echo ${{ job.status }}
-      - name: fail the job
-        run: exit 1
+#      - name: fail the job
+#        run: exit 1
         
-      - name: set_step_status
-        if: ${{ job.status == 0 }}
-        run: |
-          echo ::set-env JOB_STATUS_CODE=2
+#      - name: set_step_status
+#        if: ${{ job.status == 0 }}
+#        run: |
+#          echo ::set-env JOB_STATUS_CODE=2
       ######## Setup JDK 11 ########
       - name: Set up JDK 11
         id: setup_jdk
@@ -97,7 +97,7 @@ jobs:
     runs-on: ubuntu-latest 
     steps:
       - uses: actions/checkout@v2
-        if: ${{ job.status == 2 }}
+ #       if: ${{ job.status == 2 }}
       - name: SonarCloud Scan
         run: mvn -B sonar:sonar -Dsonar.host.url=https://sonarcloud.io -Dsonar.organization=pintu-gupta-github -Dsonar.projectKey=pintu-gupta-github
         #uses: sonarsource/sonarcloud-github-action@master
