Update action.yml

diff --git a/.github/workflows/action.yml b/.github/workflows/action.yml
--- a/.github/workflows/action.yml
+++ b/.github/workflows/action.yml
@@ -25,24 +25,25 @@ on:
       - '[0-9]-[0-9]-X-BRANCH'
 
 jobs:
-#  pre-commit:
-#    runs-on: ubuntu-latest 
+  pre-commit:
+    runs-on: ubuntu-latest 
 #      
-#    steps:
+    steps:
 #      - name: Set up pre-commit cache
 #        id: commit_check
 #        uses: pre-commit/action@v2.0.0
 #        with:
 #          extra_args: --files ${{steps.file_changes.outputs.files}}
 #
-#      - name: PR comment
-#        if: failure()
-#        uses: actions/github-script@v4
+      - name: PR comment
+        if: failure()
+        uses: actions/github-script@v4
 #
-#        with:
-#          github-token: ${{secrets.GIT_TOKEN}}
+        with:
+          github-token: ${{secrets.GIT_TOKEN}}
+          run: echo "FAILURE"
+          run: exit 1
 #          script: |
-#
 #            github.issues.createComment({
 #              issue_number: context.issue.number,
 #              owner: context.repo.owner,
