updated version

diff --git a/.github/workflows/CI_CD.yml b/.github/workflows/CI_CD.yml
--- a/.github/workflows/CI_CD.yml
+++ b/.github/workflows/CI_CD.yml
@@ -10,6 +10,65 @@ env:
   IMAGE_NAME: "romi293/java_github_actions:latest"
 
 jobs:
+
+  versioning:
+    runs-on: ubuntu-latest
+
+    env: 
+      CURRENT_VERSION: "1.0.0"
+
+    steps:
+      - name: Determine Version Type
+        id: version
+        run: |
+          # Extract commit message from the latest commit
+          COMMIT_MESSAGE=$(git log -1 --pretty=format:%s)
+          echo "Commit Message: $COMMIT_MESSAGE"
+          
+          # Determine version type based on commit message
+          if [[ $COMMIT_MESSAGE == *"feature"* ]]; then
+            echo "::set-output name=version_type::minor"
+          elif [[ $COMMIT_MESSAGE == *"fix"* || $COMMIT_MESSAGE == *"bug"* ]]; then
+            echo "::set-output name=version_type::patch"
+          else
+            echo "::set-output name=version_type::major"
+          fi
+  
+      - name: Use Version Type
+        run: |
+          # Retrieve the version type from the previous step
+          VERSION_TYPE=$(echo "${{ steps.version.outputs.version_type }}")
+          echo "Version Type: $VERSION_TYPE"
+          
+          if [[ "$VERSION_TYPE" == "major" ]]; then
+            echo "Incrementing MAJOR version"
+          elif [[ "$VERSION_TYPE" == "minor" ]]; then
+            echo "Incrementing MINOR version"
+          else
+            echo "Incrementing PATCH version"
+          fi
+
+      - name: Increament
+        run: |
+          case $VERSION_TYPE in
+          "major")
+            NEW_VERSION=$(echo $CURRENT_VERSION | awk -F. -v OFS=. '{$1++; print}')
+            ;;
+          "minor")
+            NEW_VERSION=$(echo $CURRENT_VERSION | awk -F. -v OFS=. '{$2++; print}')
+            ;;
+          "patch")
+            NEW_VERSION=$(echo $CURRENT_VERSION | awk -F. -v OFS=. '{$3++; print}')
+            ;;
+          *)
+            echo "Invalid version type"
+            exit 1
+            ;;
+          esac
+          echo "New Version: $NEW_VERSION"
+
+########################################################
+  
   build:
     runs-on: ubuntu-latest
 
@@ -76,25 +135,25 @@ jobs:
 
 ########################################################
 
-  update_version:
-    runs-on: ubuntu-latest
+  # update_version:
+  #   runs-on: ubuntu-latest
 
-    steps:
-      - name: Increase jar patch version
-        id: version
-        run: |
-          echo VERSION: $(mvn help:evaluate -Dexpression=project.version -q -DforceStdout)
-          #cd ../../.././
-          # mvn versions:set -DnewVersion=1.0.$(($(mvn help:evaluate -Dexpression=project.version -q -DforceStdout | 
-          # awk -F '.' '{print $3}')+1)) -DgenerateBackupPoms=false
-          # echo blabla
-          echo NEW VERSION: $(mvn help:evaluate -Dexpression=project.version -q -DforceStdout)
+  #   steps:
+  #     - name: Increase jar patch version
+  #       id: version
+  #       run: |
+  #         echo VERSION: $(mvn help:evaluate -Dexpression=project.version -q -DforceStdout)
+  #         #cd ../../.././
+  #         # mvn versions:set -DnewVersion=1.0.$(($(mvn help:evaluate -Dexpression=project.version -q -DforceStdout | 
+  #         # awk -F '.' '{print $3}')+1)) -DgenerateBackupPoms=false
+  #         # echo blabla
+  #         echo NEW VERSION: $(mvn help:evaluate -Dexpression=project.version -q -DforceStdout)
           
-      - name: Increment Version
-        run: | 
-          mvn versions:set -DnewVersion=1.0.$(($(mvn help:evaluate -Dexpression=project.version -q -DforceStdout |
-          awk -F '.' '{print $3}')+1)) -DgenerateBackupPoms=false  
-          echo NEW VERSION: $(mvn help:evaluate -Dexpression=project.version -q -DforceStdout)
+  #     - name: Increment Version
+  #       run: | 
+  #         mvn versions:set -DnewVersion=1.0.$(($(mvn help:evaluate -Dexpression=project.version -q -DforceStdout |
+  #         awk -F '.' '{print $3}')+1)) -DgenerateBackupPoms=false  
+  #         echo NEW VERSION: $(mvn help:evaluate -Dexpression=project.version -q -DforceStdout)
 
   
         # mvn -B versions:set -DnewVersion=${{ github.event.release.tag_name }} -DgenerateBackupPoms=false
