versioning-3

diff --git a/.github/workflows/maven-publish.yml b/.github/workflows/maven-publish.yml
--- a/.github/workflows/maven-publish.yml
+++ b/.github/workflows/maven-publish.yml
@@ -5,6 +5,17 @@ on:
     branches:
       - main
       - '**'
+  workflow_dispatch:
+    inputs:
+      version_bump:
+        description: 'Version bump type'
+        required: true
+        default: 'patch'
+        type: choice
+        options:
+          - major
+          - minor
+          - patch
 
 jobs:
   build:
@@ -49,10 +60,48 @@ jobs:
         username: ${{ secrets.DOCKER_USERNAME }}
         password: ${{ secrets.DOCKER_PASSWORD }}
 
-    - name: Extract Git Commit SHA
-      id: vars
-      run: echo "GIT_COMMIT=$(git rev-parse --short HEAD)" >> $GITHUB_ENV
+    - name: Get the current version
+      id: get_version
+      run: |
+        VERSION=$(git describe --tags $(git rev-list --tags --max-count=1))
+        if [ -z "$VERSION" ]; then
+          VERSION="0.0.0"
+        fi
+        echo "VERSION=$VERSION" >> $GITHUB_ENV
 
+    - name: Bump version
+      id: bump_version
+      run: |
+        VERSION=${{ env.VERSION }}
+        IFS='.' read -r -a VERSION_PARTS <<< "$VERSION"
+        case ${{ github.event.inputs.version_bump }} in
+          major)
+            VERSION_PARTS[0]=$((VERSION_PARTS[0] + 1))
+            VERSION_PARTS[1]=0
+            VERSION_PARTS[2]=0
+            ;;
+          minor)
+            VERSION_PARTS[1]=$((VERSION_PARTS[1] + 1))
+            VERSION_PARTS[2]=0
+            ;;
+          patch)
+            VERSION_PARTS[2]=$((VERSION_PARTS[2] + 1))
+            ;;
+          *)
+            echo "Invalid VERSION_BUMP: ${{ github.event.inputs.version_bump }}"
+            exit 1
+            ;;
+        esac
+        NEW_VERSION="${VERSION_PARTS[0]}.${VERSION_PARTS[1]}.${VERSION_PARTS[2]}"
+        echo "NEW_VERSION=$NEW_VERSION" >> $GITHUB_ENV
+
+    - name: Create new tag
+      run: |
+        git config --global user.email "you@example.com"
+        git config --global user.name "GitHub Actions"
+        git tag ${{ env.NEW_VERSION }}
+        git push origin ${{ env.NEW_VERSION }}
+    
     - name: Build and push Docker image
       uses: docker/build-push-action@v4
       with:
@@ -60,4 +109,4 @@ jobs:
         push: true
         tags: |
           ${{ secrets.DOCKER_USERNAME }}/my-app:latest
-          ${{ secrets.DOCKER_USERNAME }}/my-app:${{ env.GIT_COMMIT }}
+          ${{ secrets.DOCKER_USERNAME }}/my-app:${{ env.NEW_VERSION }}
